title: <strong>Joshua</strong> Draxten
email: drxtn@jsh.nyc
description: <a href="#">Simple is better than complex.</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: joshuadraxten
github_username:  joshuadraxten

# Build settings
markdown: kramdown
permalink: /:categories/:title:output_ext
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
